### PR TITLE
Add support for personal access tokens

### LINKED ISSUE #93: Add support for personal access tokens
#### Why should this feature be added?
Users should be able to manipulate their personal access tokens from the command line.

#### How would you like the feature to work?
Similar to all other csctl commands. We should support create, get, and delete operations for access tokens. Get and delete operations should take an ID argument, whereas create operations should take a name flag.

#### What alternatives have been considered?
N/A

#### Additional Context
N/A

### PR DESCRIPTION
**Pull request by normanjoyner**
### Description

 #### What does this pull request accomplish?
Adds support for creating, deleting, and fetching access tokens.

 #### What issue(s) does this fix?
* Fixes #93 

 #### Additional Considerations
Access token support is currently only on stage. We should hold on merging until functionality exists on production. Marking as blocked as such.

 ### Testing

 #### Setup
N/A

 #### Instructions
Run tests:
* `make test`

Manually test functionality:
* `csctl create access-token —name test`
* `csctl get access-tokens`
* `csctl get access-token f1697ebf-4a63-4961-a15a-578f2a63653e`
* `csctl delete access-token f1697ebf-4a63-4961-a15a-578f2a63653e`

 ### Dependencies
N/A

### CODE REVIEW

**Comment by mattkelly** [comment]
Looks good in general; the one nit is caught by the linter. I just have some more general questions around PATs.

Can a PAT be used as the `token` for requests in the config file? Is there a flow that makes sense where we do essentially [this](https://github.com/containership/csctl/pull/76/files) but a PAT is provided / automatically placed in the config file instead, or do we want to leave that as-is?

How long is a PAT valid for?

**Comment by normanjoyner** [comment]
I’ll get that fixed up here shortly. PATs can certainly be used for the token in the config file. The user will need a valid token in the first place to create the token, so a flag to replace the current token could make sense, but I’m not sure how helpful this would really be. Tokens are valid for 1000 years and can be “revoked” by deleting the access token from the API.

**Comment by normanjoyner** [comment]
Having an easy way / documentation to set the token from an access token copied from the Containership Cloud UI would be helpful.

**Comment by normanjoyner** [comment]
Added new commit with updates. I’ll squash it upon approval.

**Comment by normanjoyner** [comment]
Squashed and tested against production. Should be good to go now.

**Pull request merged**
