### PR TITLE
Add Docker image support

### LINKED ISSUE #96: Provide a Docker image
#### What is the current behavior?

Let's provide a Docker image so users can run `csctl` without installing anything. Especially useful before we have releases so users can just run the `latest` tag.

#### What is the expected behavior?

I can `docker run` a container with the usual args.

#### Additional Context
N/A

### PR DESCRIPTION
**Pull request by mattkelly**
#### What does this pull request accomplish?

Add Docker image support - see README updates.

 #### What issue(s) does this fix?
* Closes #96

 #### Additional Considerations

 ### Testing

 See the README for the command I used to test this.

 ### Dependencies
* None

### CODE REVIEW

**Comment by mattkelly** [comment]
This is currently rebased on top of #99 to pick up the `--token` changes. I'll rebase onto master once that's merged.

**Comment by mattkelly** [comment]
@normanjoyner can you please create `containership/csctl` on Docker Hub when you get a chance 🙏

**Comment by normanjoyner** [comment]
@mattkelly created

**Comment by mattkelly** [comment]
#99 was supposed to be merged and then this rebased, as this is `do-not-merge`. Whoops 🤷‍♂️

**Pull request merged**
