### PR TITLE
Little tweak on Makefile phony rules

### PR DESCRIPTION
**Pull request by noahp**
To be merged after #1 !

This PR just moves the `.PHONY` declarations in the Makefile runner to right before the individual rules, to hopefully be more maintainable.

### CODE REVIEW

**Comment by mattkelly** [comment]
Thanks! This is definitely a better approach. Last commit lgtm;  I'll approve and merge once #1 is in. 🚀

**Comment by mattkelly** [comment]
@noahp looks like you made these changes just before the final rebase I did yesterday. Do you mind fixing it up quick so I can merge? 🙏

**Comment by noahp** [comment]
Oh you got it dude! no worries.

**Comment by mattkelly** [comment]
Thanks for your contribution!

**Pull request merged**
