### PR TITLE
Remove hardcoding of CNI implementations

### PR DESCRIPTION
**Pull request by mattkelly**
#### What does this pull request accomplish?

Remove hardcoding of CNI implementations

We should delegate validation and defaulting to cloud.

 #### What issue(s) does this fix?
 None

 #### Additional Considerations

 ### Testing

 I've been using this all day for CNI testing :)

 ### Dependencies
 None

### CODE REVIEW

**Comment by mattkelly** [comment]
Fixed tests. Whoops.

**Comment by nicktate** [comment]
Is cloud already defaulting now across the board or after this change are you required to specify a `--plugin-cni` flag on cluster create?

**Comment by mattkelly** [comment]
Ah jeez good point, this is not the correct change (I've been using `--plugin-cni`). Now I have to actually use my brain.

```
Error: server responded with status 400: {"message":"Invalid body: \"implementation\" is not allowed to be empty."}
```

**Comment by mattkelly** [comment]
Actually just closing this as the change will be fundamentally different

**Pull request closed without merging**
