### PR TITLE
Adds the cloud auth swagger client

### PR DESCRIPTION
**Pull request by nicktate**
### Description

 #### What does this pull request accomplish?
Adds basic swagger definition for the auth api to include the `login/{method}` route. Currently only supports email. See additional considerations below for more information.

 #### What issue(s) does this fix?
Related to https://github.com/containership/csctl/issues/3. Precursor to implementing commands.

 #### Additional Considerations
`github` and `bitbucket` will be broken out into new issues as they will require a mini o-auth web server for a callback URL.

### CODE REVIEW

**Comment by mattkelly** [comment]
@nicktate please rebase to fix CI issues

**Comment by nicktate** [comment]
@mattkelly rebased and updated for `nits`

**Comment by ashleyschuett** [comment]
we need to add the debugger here now as well

**Comment by mattkelly** [comment]
@ashleyschuett is correct; I prematurely clicked the button - apologies!

**Pull request merged**
